IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'invitation' AND TABLE_SCHEMA = 'dbo' AND COLUMN_NAME = 'isMigrated')
    BEGIN
        ALTER TABLE invitation
        ADD isMigrated BIT DEFAULT 0 NOT NULL
    END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'dbo' AND COLUMN_NAME = 'isMigrated')
    BEGIN
        ALTER TABLE [user]
        ADD isMigrated BIT DEFAULT 0 NOT NULL
    END
GO
